### ISSUE TITLE
Arithmetic exception upon first launch

### ISSUE THREAD

**Issue by HugoKooijman** [ProgrammingLife2016/PL3-2016#36]
Happens when launching the application with the example.gfa file.

Caused by: java.lang.ArithmeticException: / by zero
    at coordinates.CoordinateDetermination.calcCoords(CoordinateDetermination.java:67)
    at db.DatabaseProcessor.updateCoordinates(DatabaseProcessor.java:34)

**Comment by HugoKooijman** [comment]
Issue fixed by @RobKapel .
